-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_concentrate_reviews" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "reviewId" TEXT NOT NULL,
    "nomCommercial" TEXT NOT NULL,
    "hashmaker" TEXT,
    "laboratoire" TEXT,
    "cultivarsUtilises" TEXT,
    "photos" TEXT,
    "parentFlowerReviewId" TEXT,
    "extractionPipelineId" TEXT,
    "extractionPipelineGithubId" TEXT,
    "extractionTimelineConfig" TEXT,
    "extractionTimelineData" TEXT,
    "methodeExtraction" TEXT,
    "purificationPipelineId" TEXT,
    "purificationPipelineGithubId" TEXT,
    "thcPercent" REAL,
    "cbdPercent" REAL,
    "cbgPercent" REAL,
    "cbcPercent" REAL,
    "cbnPercent" REAL,
    "thcvPercent" REAL,
    "otherCannabinoids" TEXT,
    "terpeneProfile" TEXT,
    "labReportUrl" TEXT,
    "terpeneFileUrl" TEXT,
    "couleurTransparence" REAL,
    "viscosite" REAL,
    "pureteVisuelle" REAL,
    "melting" REAL,
    "residus" REAL,
    "pistils" REAL,
    "moisissure" REAL,
    "fideliteCultivars" REAL,
    "intensiteAromatique" REAL,
    "notesDominantes" TEXT,
    "notesSecondaires" TEXT,
    "durete" REAL,
    "densiteTactile" REAL,
    "friabiliteViscositeMelting" REAL,
    "meltingResidus" REAL,
    "intensite" REAL,
    "agressivitePiquant" REAL,
    "dryPuff" TEXT,
    "inhalation" TEXT,
    "expiration" TEXT,
    "monteeRapidite" REAL,
    "intensiteEffets" REAL,
    "effetsChoisis" TEXT,
    "effetsFiltre" TEXT,
    "methodeConsommation" TEXT,
    "dosageUtilise" TEXT,
    "dureeEffets" TEXT,
    "curingPipelineId" TEXT,
    "curingPipelineGithubIdConcentrate" TEXT,
    "curingDuration" INTEGER,
    "curingType" TEXT,
    "curingInterval" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "concentrate_reviews_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "reviews" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "concentrate_reviews_parentFlowerReviewId_fkey" FOREIGN KEY ("parentFlowerReviewId") REFERENCES "reviews" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_concentrate_reviews" ("agressivitePiquant", "cbcPercent", "cbdPercent", "cbgPercent", "cbnPercent", "couleurTransparence", "createdAt", "cultivarsUtilises", "curingDuration", "curingInterval", "curingPipelineGithubIdConcentrate", "curingPipelineId", "curingType", "densiteTactile", "dosageUtilise", "dryPuff", "dureeEffets", "durete", "effetsChoisis", "effetsFiltre", "expiration", "extractionPipelineGithubId", "extractionPipelineId", "extractionTimelineConfig", "extractionTimelineData", "fideliteCultivars", "friabiliteViscositeMelting", "hashmaker", "id", "inhalation", "intensite", "intensiteAromatique", "intensiteEffets", "labReportUrl", "laboratoire", "melting", "meltingResidus", "methodeConsommation", "methodeExtraction", "moisissure", "monteeRapidite", "nomCommercial", "notesDominantes", "notesSecondaires", "otherCannabinoids", "photos", "pistils", "pureteVisuelle", "purificationPipelineGithubId", "purificationPipelineId", "residus", "reviewId", "terpeneFileUrl", "terpeneProfile", "thcPercent", "thcvPercent", "updatedAt", "viscosite") SELECT "agressivitePiquant", "cbcPercent", "cbdPercent", "cbgPercent", "cbnPercent", "couleurTransparence", "createdAt", "cultivarsUtilises", "curingDuration", "curingInterval", "curingPipelineGithubIdConcentrate", "curingPipelineId", "curingType", "densiteTactile", "dosageUtilise", "dryPuff", "dureeEffets", "durete", "effetsChoisis", "effetsFiltre", "expiration", "extractionPipelineGithubId", "extractionPipelineId", "extractionTimelineConfig", "extractionTimelineData", "fideliteCultivars", "friabiliteViscositeMelting", "hashmaker", "id", "inhalation", "intensite", "intensiteAromatique", "intensiteEffets", "labReportUrl", "laboratoire", "melting", "meltingResidus", "methodeConsommation", "methodeExtraction", "moisissure", "monteeRapidite", "nomCommercial", "notesDominantes", "notesSecondaires", "otherCannabinoids", "photos", "pistils", "pureteVisuelle", "purificationPipelineGithubId", "purificationPipelineId", "residus", "reviewId", "terpeneFileUrl", "terpeneProfile", "thcPercent", "thcvPercent", "updatedAt", "viscosite" FROM "concentrate_reviews";
DROP TABLE "concentrate_reviews";
ALTER TABLE "new_concentrate_reviews" RENAME TO "concentrate_reviews";
CREATE UNIQUE INDEX "concentrate_reviews_reviewId_key" ON "concentrate_reviews"("reviewId");
CREATE INDEX "concentrate_reviews_reviewId_idx" ON "concentrate_reviews"("reviewId");
CREATE INDEX "concentrate_reviews_nomCommercial_idx" ON "concentrate_reviews"("nomCommercial");
CREATE TABLE "new_hash_reviews" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "reviewId" TEXT NOT NULL,
    "nomCommercial" TEXT NOT NULL,
    "hashmaker" TEXT,
    "laboratoire" TEXT,
    "cultivarsUtilises" TEXT,
    "photos" TEXT,
    "parentFlowerReviewId" TEXT,
    "separationPipelineId" TEXT,
    "separationPipelineGithubId" TEXT,
    "separationTimelineConfig" TEXT,
    "separationTimelineData" TEXT,
    "methodeSeparation" TEXT,
    "nombrePasses" INTEGER,
    "temperatureEau" REAL,
    "tailleMailles" TEXT,
    "typeMatierePremiere" TEXT,
    "qualiteMatierePremiere" REAL,
    "rendementEstime" REAL,
    "tempsTotalSeparation" INTEGER,
    "purificationPipelineId" TEXT,
    "purificationPipelineGithubId" TEXT,
    "thcPercent" REAL,
    "cbdPercent" REAL,
    "cbgPercent" REAL,
    "cbcPercent" REAL,
    "cbnPercent" REAL,
    "thcvPercent" REAL,
    "otherCannabinoids" TEXT,
    "terpeneProfile" TEXT,
    "labReportUrl" TEXT,
    "terpeneFileUrl" TEXT,
    "couleurTransparence" REAL,
    "pureteVisuelle" REAL,
    "densiteVisuelle" REAL,
    "pistils" REAL,
    "moisissure" REAL,
    "graines" REAL,
    "fideliteCultivars" REAL,
    "intensiteAromatique" REAL,
    "notesDominantes" TEXT,
    "notesSecondaires" TEXT,
    "durete" REAL,
    "densiteTactile" REAL,
    "friabiliteViscositeMelting" REAL,
    "meltingResidus" REAL,
    "intensite" REAL,
    "agressivitePiquant" REAL,
    "dryPuff" TEXT,
    "inhalation" TEXT,
    "expiration" TEXT,
    "monteeRapidite" REAL,
    "intensiteEffets" REAL,
    "effetsChoisis" TEXT,
    "effetsFiltre" TEXT,
    "methodeConsommation" TEXT,
    "dosageUtilise" TEXT,
    "dureeEffets" TEXT,
    "curingPipelineId" TEXT,
    "curingPipelineGithubId" TEXT,
    "curingDuration" INTEGER,
    "curingType" TEXT,
    "curingInterval" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "hash_reviews_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "reviews" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "hash_reviews_parentFlowerReviewId_fkey" FOREIGN KEY ("parentFlowerReviewId") REFERENCES "reviews" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_hash_reviews" ("agressivitePiquant", "cbcPercent", "cbdPercent", "cbgPercent", "cbnPercent", "couleurTransparence", "createdAt", "cultivarsUtilises", "curingDuration", "curingInterval", "curingPipelineGithubId", "curingPipelineId", "curingType", "densiteTactile", "densiteVisuelle", "dosageUtilise", "dryPuff", "dureeEffets", "durete", "effetsChoisis", "effetsFiltre", "expiration", "fideliteCultivars", "friabiliteViscositeMelting", "graines", "hashmaker", "id", "inhalation", "intensite", "intensiteAromatique", "intensiteEffets", "labReportUrl", "laboratoire", "meltingResidus", "methodeConsommation", "methodeSeparation", "moisissure", "monteeRapidite", "nomCommercial", "nombrePasses", "notesDominantes", "notesSecondaires", "otherCannabinoids", "photos", "pistils", "pureteVisuelle", "purificationPipelineGithubId", "purificationPipelineId", "qualiteMatierePremiere", "rendementEstime", "reviewId", "separationPipelineGithubId", "separationPipelineId", "separationTimelineConfig", "separationTimelineData", "tailleMailles", "temperatureEau", "tempsTotalSeparation", "terpeneFileUrl", "terpeneProfile", "thcPercent", "thcvPercent", "typeMatierePremiere", "updatedAt") SELECT "agressivitePiquant", "cbcPercent", "cbdPercent", "cbgPercent", "cbnPercent", "couleurTransparence", "createdAt", "cultivarsUtilises", "curingDuration", "curingInterval", "curingPipelineGithubId", "curingPipelineId", "curingType", "densiteTactile", "densiteVisuelle", "dosageUtilise", "dryPuff", "dureeEffets", "durete", "effetsChoisis", "effetsFiltre", "expiration", "fideliteCultivars", "friabiliteViscositeMelting", "graines", "hashmaker", "id", "inhalation", "intensite", "intensiteAromatique", "intensiteEffets", "labReportUrl", "laboratoire", "meltingResidus", "methodeConsommation", "methodeSeparation", "moisissure", "monteeRapidite", "nomCommercial", "nombrePasses", "notesDominantes", "notesSecondaires", "otherCannabinoids", "photos", "pistils", "pureteVisuelle", "purificationPipelineGithubId", "purificationPipelineId", "qualiteMatierePremiere", "rendementEstime", "reviewId", "separationPipelineGithubId", "separationPipelineId", "separationTimelineConfig", "separationTimelineData", "tailleMailles", "temperatureEau", "tempsTotalSeparation", "terpeneFileUrl", "terpeneProfile", "thcPercent", "thcvPercent", "typeMatierePremiere", "updatedAt" FROM "hash_reviews";
DROP TABLE "hash_reviews";
ALTER TABLE "new_hash_reviews" RENAME TO "hash_reviews";
CREATE UNIQUE INDEX "hash_reviews_reviewId_key" ON "hash_reviews"("reviewId");
CREATE INDEX "hash_reviews_reviewId_idx" ON "hash_reviews"("reviewId");
CREATE INDEX "hash_reviews_nomCommercial_idx" ON "hash_reviews"("nomCommercial");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
