-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_flower_reviews" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "reviewId" TEXT NOT NULL,
    "nomCommercial" TEXT NOT NULL,
    "farm" TEXT,
    "varietyType" TEXT,
    "breeder" TEXT,
    "variety" TEXT,
    "geneticType" TEXT,
    "indicaPercent" INTEGER,
    "sativaPercent" INTEGER,
    "parentage" TEXT,
    "phenotypeCode" TEXT,
    "geneticTreeId" TEXT,
    "culturePipelineId" TEXT,
    "culturePipelineGithubId" TEXT,
    "cultureTimelineConfig" TEXT,
    "cultureTimelineData" TEXT,
    "cultureMode" TEXT,
    "cultureSpaceType" TEXT,
    "cultureSubstrat" TEXT,
    "cultureStartDate" DATETIME,
    "cultureEndDate" DATETIME,
    "cultureDuration" INTEGER,
    "cultureSeason" TEXT,
    "thcPercent" REAL,
    "cbdPercent" REAL,
    "otherCannabinoids" TEXT,
    "terpeneProfile" TEXT,
    "labReportUrl" TEXT,
    "consumptionMethod" TEXT,
    "dosage" REAL,
    "effectDuration" TEXT,
    "effectProfiles" TEXT,
    "sideEffects" TEXT,
    "effectOnset" TEXT,
    "effectLength" TEXT,
    "preferredUse" TEXT,
    "couleurScore" REAL,
    "couleurNuancier" TEXT,
    "densiteVisuelle" REAL,
    "trichomesScore" REAL,
    "pistilsScore" REAL,
    "manucureScore" REAL,
    "moisissureScore" REAL,
    "grainesScore" REAL,
    "notesOdeursDominantes" TEXT,
    "notesOdeursSecondaires" TEXT,
    "aromesInhalation" TEXT,
    "saveurBouche" TEXT,
    "intensiteAromeScore" REAL,
    "complexiteAromeScore" REAL,
    "fideliteAromeScore" REAL,
    "dureteScore" REAL,
    "densiteTactileScore" REAL,
    "elasticiteScore" REAL,
    "collantScore" REAL,
    "intensiteGoutScore" REAL,
    "agressiviteScore" REAL,
    "dryPuffNotes" TEXT,
    "inhalationNotes" TEXT,
    "expirationNotes" TEXT,
    "monteeScore" REAL,
    "intensiteEffetScore" REAL,
    "effetsChoisis" TEXT,
    "effetsFiltre" TEXT,
    "curingPipelineId" TEXT,
    "curingPipelineGithubId" TEXT,
    "curingTimelineConfig" TEXT,
    "curingTimelineData" TEXT,
    "curingTemperature" REAL,
    "curingHumidity" REAL,
    "curingDuration" INTEGER,
    "curingType" TEXT,
    "curingInterval" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "flower_reviews_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "reviews" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "flower_reviews_geneticTreeId_fkey" FOREIGN KEY ("geneticTreeId") REFERENCES "genetic_trees" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_flower_reviews" ("agressiviteScore", "aromesInhalation", "breeder", "cbdPercent", "collantScore", "complexiteAromeScore", "consumptionMethod", "couleurNuancier", "couleurScore", "createdAt", "cultureDuration", "cultureEndDate", "cultureMode", "culturePipelineGithubId", "culturePipelineId", "cultureSeason", "cultureSpaceType", "cultureStartDate", "cultureSubstrat", "cultureTimelineConfig", "cultureTimelineData", "curingDuration", "curingHumidity", "curingInterval", "curingPipelineGithubId", "curingPipelineId", "curingTemperature", "curingTimelineConfig", "curingTimelineData", "curingType", "densiteTactileScore", "densiteVisuelle", "dosage", "dryPuffNotes", "dureteScore", "effectDuration", "effectLength", "effectOnset", "effectProfiles", "effetsChoisis", "effetsFiltre", "elasticiteScore", "expirationNotes", "farm", "fideliteAromeScore", "geneticType", "grainesScore", "id", "indicaPercent", "inhalationNotes", "intensiteAromeScore", "intensiteEffetScore", "intensiteGoutScore", "labReportUrl", "manucureScore", "moisissureScore", "monteeScore", "nomCommercial", "notesOdeursDominantes", "notesOdeursSecondaires", "otherCannabinoids", "parentage", "phenotypeCode", "pistilsScore", "preferredUse", "reviewId", "sativaPercent", "saveurBouche", "sideEffects", "terpeneProfile", "thcPercent", "trichomesScore", "updatedAt", "variety", "varietyType") SELECT "agressiviteScore", "aromesInhalation", "breeder", "cbdPercent", "collantScore", "complexiteAromeScore", "consumptionMethod", "couleurNuancier", "couleurScore", "createdAt", "cultureDuration", "cultureEndDate", "cultureMode", "culturePipelineGithubId", "culturePipelineId", "cultureSeason", "cultureSpaceType", "cultureStartDate", "cultureSubstrat", "cultureTimelineConfig", "cultureTimelineData", "curingDuration", "curingHumidity", "curingInterval", "curingPipelineGithubId", "curingPipelineId", "curingTemperature", "curingTimelineConfig", "curingTimelineData", "curingType", "densiteTactileScore", "densiteVisuelle", "dosage", "dryPuffNotes", "dureteScore", "effectDuration", "effectLength", "effectOnset", "effectProfiles", "effetsChoisis", "effetsFiltre", "elasticiteScore", "expirationNotes", "farm", "fideliteAromeScore", "geneticType", "grainesScore", "id", "indicaPercent", "inhalationNotes", "intensiteAromeScore", "intensiteEffetScore", "intensiteGoutScore", "labReportUrl", "manucureScore", "moisissureScore", "monteeScore", "nomCommercial", "notesOdeursDominantes", "notesOdeursSecondaires", "otherCannabinoids", "parentage", "phenotypeCode", "pistilsScore", "preferredUse", "reviewId", "sativaPercent", "saveurBouche", "sideEffects", "terpeneProfile", "thcPercent", "trichomesScore", "updatedAt", "variety", "varietyType" FROM "flower_reviews";
DROP TABLE "flower_reviews";
ALTER TABLE "new_flower_reviews" RENAME TO "flower_reviews";
CREATE UNIQUE INDEX "flower_reviews_reviewId_key" ON "flower_reviews"("reviewId");
CREATE INDEX "flower_reviews_reviewId_idx" ON "flower_reviews"("reviewId");
CREATE INDEX "flower_reviews_nomCommercial_idx" ON "flower_reviews"("nomCommercial");
CREATE INDEX "flower_reviews_variety_idx" ON "flower_reviews"("variety");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
